PWD = /home/mikhail/Upwork/python/cocoTB/verilog_src
COCOTB = /home/mikhail/Upwork/cocoTB/cocotb
VERILOG_SOURCES = $(PWD)/my_design.sv
TOPLEVEL = my_design
MODULE = test_my_design

include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
